name: YC Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    env:
      DOCKER_TAG: $(date +%s)
      DOCKER_NAME: cr.yandex/${{ vars.YC_REGISRTY_ID }}/${{ vars.YC_DOCKER_IMAGE_NAME }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Download YC CLI
      run: curl -sSL https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
    - name: Restart shell
      run: source "/home/runner/.bashrc"
    - name: Init YC CLI
      run: yc init -t ${{ env.YC_AUTH_KEY }}
    - name: Docker login
      run: docker login -u ${{ vars.DOCKER_LOGIN }} -p ${{ vars.DOCKER_PASSWORD }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ env.DOCKER_NAME }}/${{ env.DOCKER_TAG }}
    - name: Push the Docker image
      run: docker push ${{ env.DOCKER_NAME }}/${{ env.DOCKER_TAG }}
